#!/bin/sh

trap 'ret=$?; test $ret -ne 0; exit $ret' EXIT
sudo -v

if ! command -v xcode-select -p >/dev/null; then
  xcode-select --install
fi

if ! command -v brew >/dev/null; then
  /usr/bin/ruby -e "$(
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install
  )"

  brew bundle --file=- <<EOF
  tap 'homebrew/core'
  tap 'homebrew/bundle'
  tap 'caskroom/cask'
  tap 'caskroom/fonts'
  tap 'caskroom/versions'
EOF
fi

brew bundle --file=- <<EOF
  tap 'homebrew/core'
  tap 'homebrew/bundle'
  tap 'caskroom/fonts'
  tap 'caskroom/versions'
  tap 'caskroom/cask'
  brew 'cmatrix'
  brew 'coreutils'
  brew 'curl'
  brew 'direnv'
  brew 'git'
  brew 'findutils'
  brew 'fish'
  brew 'git-flow'
  brew 'htop'
  brew 'openssl'
  brew 'httpie'
  brew 'mas'
  brew 'reattach-to-user-namespace'
  brew 'sl'
  brew 'ssh-copy-id'
  brew 'stow'
  brew 'tmux'
  brew 'wget'
  cask 'alfred'
  cask 'atom'
  cask 'docker'
  cask 'dropbox'
  cask 'google-chrome'
  cask 'iina'
  cask 'qlcolorcode'
  cask 'qlmarkdown'
  cask 'qlstephen'
  cask 'qlvideo'
  cask 'quicklook-csv'
  cask 'quicklook-json'
  cask 'skadi'
  cask 'the-unarchiver'
  cask 'transmission'
  cask 'webpquicklook'
  cask 'caskroom/fonts/font-fira-code'
  mas '1Blocker', id: 1107421413
  mas 'Pixelmator', id: 407963104
  mas 'Radium', id: 597611879
  mas 'Textual', id: 896450579
  mas 'Transmit', id: 403388562
EOF

if ! fgrep -q '/usr/local/bin/fish' /etc/shells; then
  echo '/usr/local/bin/fish' | sudo tee -a /etc/shells
fi

if [[ ! $SHELL = '/usr/local/bin/fish' ]]; then
  chsh -s /usr/local/bin/fish
fi

if brew cask list | grep atom; then
  /Applications/Atom.app/Contents/Resources/app/apm/bin/apm install \
    duotone-dark-syntax \
    duotone-light-syntax \
    file-icons \
    hard-wrap \
    language-babel \
    lines \
    linter \
    linter-js-standard \
    pigments \
    pretty-json \
    pristine-ui \
    sort-lines
fi

echo 'Install complete.'
