#!/bin/sh

# Ask for the administrator password upfront
sudo -v

# Update existing `sudo` time stamp until `install` has finished
while true; do
  sudo -n true
  sleep 60
  kill -0 "$$" || exit
done 2>/dev/null &

# Install Xcode command line tools
if ! command -v xcode-select -p >/dev/null; then
  xcode-select --install
fi

# Install homebrew
if ! command -v brew >/dev/null; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || true
fi

# Bundle applications
brew bundle --file=- <<EOF
  brew 'bat'
  brew 'cmatrix'
  brew 'coreutils'
  brew 'curl'
  brew 'direnv'
  brew 'eza'
  brew 'fd'
  brew 'fish'
  brew 'git'
  brew 'htop'
  brew 'httpie'
  brew 'mas'
  brew 'mise'
  brew 'openssl'
  brew 'sl'
  brew 'ssh-copy-id'
  brew 'starship'
  brew 'stow'
  brew 'tree'
  brew 'wget'

  cask 'alt-tab'
  cask 'font-fira-code'
  cask 'ghostty'
  cask 'iina'
  cask 'keka'
  cask 'orbstack'
  cask 'orion'
  cask 'sensiblesidebuttons'
  cask 'signal'
  cask 'vscodium'

  mas 'Pixelmator', id: 407963104
  mas 'Xcode', id: 497799835
EOF

# Add fish to shells
if ! grep -F -q '/opt/homebrew/bin/fish' /etc/shells; then
  echo '/opt/homebrew/bin/fish' | sudo tee -a /etc/shells
fi

# Set fish as the default shell
if [ ! "${SHELL}" = '/opt/homebrew/bin/fish' ]; then
  chsh -s /opt/homebrew/bin/fish
fi

echo 'Install complete! Please restart your terminal.'
