add_newline = false

[character]
symbol = "λ ->"
error_symbol = "λ ~>"
use_symbol_for_status = true

[directory]
fish_style_pwd_dir_length = 3

[line_break]
disabled = true

[package]
symbol = "pkg "
disabled = true

[nodejs]
symbol = "no "
disabled = true

[python]
symbol = "Py "
disabled = true

[rust]
symbol = "R "
disabled = true

[golang]
symbol = "go "
disabled = true

[git_status]
deleted = "x"

[jobs]
symbol = "+ "
threshold = 0

[terraform]
symbol = "Tf "
