command_timeout = 1000

[character]
success_symbol = "[λ](green)"
error_symbol = "[λ](red)"

[directory]
fish_style_pwd_dir_length = 3

[package]
symbol = "pkg "
disabled = true

[nodejs]
symbol = ".js "
disabled = true

[python]
symbol = "Py "
disabled = true

[rust]
symbol = "R "
disabled = true

[golang]
symbol = "go "
disabled = true

[git_status]
deleted = "x"

[jobs]
symbol = "+ "
number_threshold = 0

[gcloud]
disabled = true

[docker_context]
disabled = true
